

host="127.0.0.1"
bind=":8888"
config="configs/json"

[gamedb]
host = "localhost"
user = "root"
password = "123456"
name = "gamedb"
port = 3306


[cache]
host = "localhost"
password = "123456"
name = "1"
port = 6379