// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Role {
    #[prost(string, tag = "1")]
    pub aaaaaaaaaaaaa: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub level: u32,
    #[prost(uint64, tag = "3")]
    pub exp: u64,
    #[prost(uint64, tag = "4")]
    pub gold: u64,
    #[prost(uint64, tag = "5")]
    pub diamond: u64,
}
