[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = {version="2.0.98",features=["full","extra-traits"] }
quote = "1.0.38"
log = "0.4.25"
proc-macro2 = {version = "1.0.93"}


[lib]
proc-macro = true