[package]
name = "models"
version = "0.1.0"
edition = "2021"

[dependencies]
mysql={version = "26.0.0"}
config={path="../config"}
prost = { version = "0.13.5" }
tonic = { version = "0.12.3" }

[build-dependencies]
tonic-build = { version = "0.12.3" }
